#!/bin/bash

# Script to manage timeout of the system
# Made by DRAGONO

show_help()
{
    echo
    echo "Usage: $0 [option]                                                                                                         " 
    echo "Options:                                                                                                                   "
    echo
    echo "    To disable/enable caffeine for a duration:                                                                             "
    echo
    echo "    -d, --disable-caffeine                         Turn off caffeine.                                                      "
    echo "    -e, --enable-caffeine [int(seconds)]           Enable caffeine for a duration of x seconds.                            "
    echo "    -t, --toggle-caffeine [int(seconds)]           Enable/Disable caffeine. If enabled, will be for x seconds.             "
    echo "    -l, --get-time-left                            Get the time left before caffeine will turn off.                        "
    echo "    --startup-disabled-on                          Enable caffeine at computer startup. You will have to lock manually.    "
    echo "    --startup-disabled-off                         Disable caffeine at startup.                                            "
    echo "    --startup-disabled-toggle                      Turn on/off caffeine enabled at startup.                                "
    echo "    --get-startup-disabled                         Display if this feature is on or off.                                   "
    echo
    echo "    Note: Giving a duration of -1 will means that the duration will be infinite.                                           "
    echo
    echo "    To edit/get desktop dimming/timeout:                                                                                   "
    echo
    echo "    --set-desktop-dim-time [int(seconds)]          Set the desktop time before dimming.                                    "
    echo "    --set-desktop-timeout-time [int(seconds)]      Set the desktop time before locking.                                    "
    echo "    --get-desktop-dim-time                         Display the current set dim time.                                       "
    echo "    --get-desktop-timeout-time                     Display the current set lock time.                                      "
    echo "    --desktop-dim-on                               Turn off the dimming on the desktop.                                    "
    echo "    --desktop-dim-off                              Turn on the dimming on the desktop.                                     "
    echo "    --desktop-dim-toggle                           Toggle on/off the dimming on the desktop.                               "
    echo "    --get-desktop-dim-toggle                       Display if the dim is toggled or not.                                   "
    echo
    echo "    To edit/get lockscreen dimming/timeout:                                                                                "
    echo
    echo "   --set-lockscreen-dim-time [int(seconds)]        Set the lockscreen time before dimming.                                 "
    echo "   --set-lockscreen-timeout-time [int(seconds)]    Set the lockscreen time before screen turn off.                         "
    echo "   --get-lockscreen-dim-time                       Display the current set dim time.                                       "
    echo "   --get-lockscreen-timeout-time                   Display the current set screen off time.                                "
    echo "   --lockscreen-dim-on                             Turn off the dimming on the lockscreen.                                 "
    echo "   --lockscreen-dim-off                            Turn on the dimming on the lockscreen.                                  "
    echo "   --lockscreen-dim-toggle                         Toggle on/off the dimming on the lock screen.                           "
    echo "   --get-lockscreen-dim-toggle                     Display if the dim is toggled or not.                                   "
    echo
    echo "    To show this message:                                                                                                  "
    echo
    echo "    -h, --help                              Show help.                                                                     "
}

# === CAFFEINE ===
disable_caffeine()
{
    echo "disable caffeine"
    return 0
}

enable_caffeine()
{
    local time="$1"
    echo "enable caffeine"
    return 0
}

toggle_caffeine()
{
    local time="$1"
    echo "toggle caffeine"
    return 0
}

get_time_left()
{
    echo "get time left"
    return 0
}

startup_disabled_on()
{
    echo "startup disabled on"
    return 0
}

startup_disabled_off()
{
    echo "startup disabled off"
    return 0
}

startup_disabled_toggle()
{
    echo "startup disabled toggle"
    return 0
}

get_startup_disabled()
{
    echo "get startup disabled"
    return 0
}



# === DESKTOP ===
set_desktop_dim_time()
{
    local time="$1"
    echo "set desktop dim time"
    return 0
}

set_desktop_timeout_time()
{
    local time="$1"
    echo "set desktop timeout time"
    return 0
}

get_desktop_dim_time()
{
    echo "get desktop dim time"
    return 0
}

get_desktop_timeout_time()
{
    echo "get desktop timeout time"
    return 0
}

desktop_dim_on()
{
    echo "desktop dim on"
    return 0
}

desktop_dim_off()
{
    echo "desktop dim off"
    return 0
}

desktop_dim_toggle()
{
    echo "desktop dim toggle"
    return 0
}

get_desktop_dim_toggle()
{
    echo "get desktop dim toggle"
    return 0
}



# === LOCKSCREEN ===
set_lockscreen_dim_time()
{
    local time="$1"
    echo "set lockscreen dim time"
    return 0
}

set_lockscreen_timeout_time()
{
    local time="$1"
    echo "set lockscreen timeout time"
    return 0
}

get_lockscreen_dim_time()
{
    echo "get lockscreen dim time"
    return 0
}

get_lockscreen_timeout_time()
{
    echo "get lockscreen timeout time"
    return 0
}

lockscreen_dim_on()
{
    echo "lockscreen dim on"
    return 0
}

lockscreen_dim_off()
{
    echo "lockscreen dim off"
    return 0
}

lockscreen_dim_toggle()
{
    echo "lockscreen dim toggle"
    return 0
}

get_lockscreen_dim_toggle()
{
    echo "get lockscreen dim toggle"
    return 0
}



# === MAIN SCRIPT ===
if [ $# -eq 0 ]
then
    >&2 echo "[ERROR]: No given arguments."
    show_help
    exit 1
fi

while [ $# -gt 0 ]
do
    case $1 in

        -d|--disable-caffeine)
	    disable_caffeine
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;



        -e|--enable-caffeine)
	    # Verifying passed arguments
	    if [ $# -lt 2 ]
	    then
	        >&2 echo "[FATAL]: $1: not enough arguments."
	        echo "Usage: $0 $1 [int(seconds)]"
	        show_help
	        exit 1
	    fi

	    enable_caffeine $2
	    if [ ! $? ]
	    then
	        >&2 echo "[ERROR]: $1 $2: an error occured."
	        show_help
	        exit 1
	    fi

	    shift 2
        ;;



        -t|--toggle-caffeine)
	    # Verifying passed arguments
	    if [ $# -lt 2 ]
	    then
	        >&2 echo "[FATAL]: $1: not enough arguments."
	        echo "Usage: $0 $1 [int(seconds)]"
	        show_help
	        exit 1
	    fi

	    toggle_caffeine $2
	    if [ ! $? ]
	    then
	        >&2 echo "[ERROR]: $1 $2: an error occured."
	        show_help
	        exit 1
	    fi

	    shift 2
        ;;



        -l|--get-time-left)
	    get_time_left
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;



        --startup-disabled-on)
	    startup_disabled_on
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;



        --startup-disabled-off)
	    startup_disabled_off
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;



        --startup-disabled-toggle)
	    startup_disabled_toggle
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;



        --get-startup-disabled)
	    get_startup_disabled
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;



        --set-desktop-dim-time)
	    # Verifying passed arguments
	    if [ $# -lt 2 ]
	    then
	        >&2 echo "[FATAL]: $1: not enough arguments."
	        echo "Usage: $0 $1 [int(seconds)]"
	        show_help
	        exit 1
	    fi

	    set_desktop_dim_time $2
	    if [ ! $? ]
	    then
	        >&2 echo "[ERROR]: $1 $2: an error occured."
	        show_help
	        exit 1
	    fi

	    shift 2
        ;;
        
        
        
        --set-desktop-timeout-time)
	    # Verifying passed arguments
	    if [ $# -lt 2 ]
	    then
	        >&2 echo "[FATAL]: $1: not enough arguments."
	        echo "Usage: $0 $1 [int(seconds)]"
	        show_help
	        exit 1
	    fi

	    set_desktop_timeout_time $2
	    if [ ! $? ]
	    then
	        >&2 echo "[ERROR]: $1 $2: an error occured."
	        show_help
	        exit 1
	    fi

	    shift 2
        ;;
        
        
        
        --get-desktop-dim-time)
	    get_desktop_dim_time
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --get-desktop-timeout-time)
	    get_desktop_dim_time
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --desktop-dim-on)
	    desktop_dim_on
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --desktop-dim-off)
	    desktop_dim_off
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --desktop-dim-toggle)
	    desktop_dim_toggle
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --get-desktop-dim-toggle)
	    get_desktop_dim_toggle
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --set-lockscreen-dim-time)
	    # Verifying passed arguments
	    if [ $# -lt 2 ]
	    then
	        >&2 echo "[FATAL]: $1: not enough arguments."
	        echo "Usage: $0 $1 [int(seconds)]"
	        show_help
	        exit 1
	    fi

	    set_lockscreen_dim_time $2
	    if [ ! $? ]
	    then
	        >&2 echo "[ERROR]: $1 $2: an error occured."
	        show_help
	        exit 1
	    fi

	    shift 2
        ;;
        
        
        
        --set-lockscreen-timeout-time)
	    # Verifying passed arguments
	    if [ $# -lt 2 ]
	    then
	        >&2 echo "[FATAL]: $1: not enough arguments."
	        echo "Usage: $0 $1 [int(seconds)]"
	        show_help
	        exit 1
	    fi

	    set_lockscreen_timeout_time $2
	    if [ ! $? ]
	    then
	        >&2 echo "[ERROR]: $1 $2: an error occured."
	        show_help
	        exit 1
	    fi

	    shift 2
        ;;
        
        
        
        --get-lockscreen-dim-time)
	    get_lockscreen_dim_time
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --get-lockscreen-timeout-time)
	    get_lockscreen_dim_time
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --lockscreen-dim-on)
	    lockscreen_dim_on
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --lockscreen-dim-off)
	    lockscreen_dim_off
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --lockscreen-dim-toggle)
	    lockscreen_dim_toggle
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        --get-lockscreen-dim-toggle)
	    get_lockscreen_dim_toggle
	    if [ ! $? ]
	    then
	        >&2 echo "[FATAL]: $1: an error occured."
	        show_help	
	        exit 1
	    fi

	    shift 1
        ;;
        
        
        
        -h|--help)
            show_help
            shift 1
        ;;

        *)
            echo "[ERROR]: Unknown option: $1"
            show_help
            exit 1
        ;;

    esac
done


